---
title: "test"
output:
  pdf_document: default
  html_document: default
---

```{r}
library(ggplot2)
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
ori = readRDS("ori.RDS")
```


## Creación de tablas de contingencia

```{r}
crearTabla <- function(variable1, variable2){
  tabla <- table(variable1, variable2)
  nueva_tabla <- as.data.frame(tabla)
  grafica <- ggplot(data = nueva_tabla, mapping = aes(x=variable1, y=variable2, fill=Freq)) + geom_tile()
  return(grafica + scale_fill_gradient2(low = "white",  high = "red"))
}
```

```{r}
tabla <- table(ori$expo_vt, ori$impo_cv)
tabla <- as.data.frame(tabla)
grafica <- ggplot(data = tabla, mapping = aes(x=Var1, y=Var2, fill=Freq)) + geom_tile()
grafica = grafica + scale_fill_gradient2(low = "white",  high = "red")
grafica
```
```{r}
crearTabla(ori$impo_cv, ori$expo_vt)
```

```{r}
crearTabla(ori$rotacion_cxc, ori$rotacion_cxp)
```
```{r}
crearTabla(ori$tiene_ventas_electronicas, ori$tiene_ventas_fisicas)
```
```{r}
crearTabla(ori$cxc, ori$cxp)
```
```{r}
crearTabla(ori$totalinventory, ori$rotacion_inventarios)
```



