---
title: "Experimento Categóricos"
output: html_document
---

```{r}
library(corrplot)
library(ggbiplot)
```
## Creación de tablas de contingencia
```{r}
crearTabla <- function(variable1, variable2){
  tabla <- table(variable1, variable2)
  nueva_tabla <- as.data.frame(tabla)
  grafica <- ggplot(data = nueva_tabla, mapping = aes(x=variable1, y=variable2, fill=Freq)) + geom_tile()
  return(grafica + scale_fill_gradient2(low = "white",  high = "red"))
}
```

## Lectura de los datos:

```{r}
categoricos <- readRDS("categoricos.RDS")
```


```{r}
table(categoricos$impo_cv[which(clusters==1)])
table(categoricos$impo_cv[which(clusters==2)])

table(categoricos$impo_cv[which(clusters==3)])

table(categoricos$impo_cv[which(clusters==4)])

```

```{r}
categoricos <- select(categoricos, -pagos_pj)
```


```{r}
correlacion_original <- cor(categoricos[ , -length(categoricos)]) 
corrplot(correlacion_original)
```

## Creación de nuevas variables:

### Impo + expo:


```{r}
crearTabla(categoricos$impo_cv, categoricos$expo_vt)
```
```{r}
table(categoricos$expo_vt, categoricos$impo_cv)

```

```{r}
prueba <- select(categoricos, impo_cv, expo_vt)
pivot_longer(prueba, names_to = c("impo_cv", "expo_vt"))
barplot(prueba)

```


```{r}
impo_expo <- categoricos$impo_cv -  categoricos$expo_vt
```

### Cuentas por cobrar y pagar:

```{r}
cxpc <- categoricos$cxc + categoricos$cxp 
```

### Ventas físicas y electrónicas:

```{r}
tiene_ventas <- categoricos$tiene_ventas_electronicas + categoricos$tiene_ventas_fisicas
```

### Recaudos totales

```{r}
recaudos <- categoricos$recaudos_pj + categoricos$recaudos_pn
```

### Pagos totales
```{r}
pagos <- categoricos$pagos_pj + categoricos$pagos_pn
```


```{r}
pca_cate <- prcomp(select(categoricos, -nit))
ggbiplot(pca_cate)
```


```{r}
datos <- pca_cate$rotation

```


